/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.math.graphic.menus;

import ec.edu.espe.math.geometry.shapes.circumference.*;
import ec.edu.espe.math.geometry.shapes.quadrilaterals.*;
import ec.edu.espe.math.geometry.shapes.triangles.*;
import ec.edu.espe.math.geometry.solids.cirfumference.Sphere;
import ec.edu.espe.math.geometry.solids.cones.Cone;
import ec.edu.espe.math.geometry.solids.cubes.Cube;
import ec.edu.espe.math.geometry.solids.cylinders.Cylinder;
import ec.edu.espe.math.geometry.solids.frustums.Frustum;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class FrmSolidsMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmShapesMenu
     */
    public FrmSolidsMenu() {
        initComponents();
        this.jpnMaster.setVisible(true);
        initializePanelsSolids();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCone = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jpnMaster = new javax.swing.JPanel();
        jpnCube = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnCalculateCube = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSideCube = new javax.swing.JTextField();
        jpnSphere = new javax.swing.JPanel();
        btnCalculateSphere = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRadiusSphere = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHeighSphere = new javax.swing.JTextField();
        jpnCylinder = new javax.swing.JPanel();
        btnCalculateCylinder = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHeighCylinder = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRadiusCylinder = new javax.swing.JTextField();
        jpnCone = new javax.swing.JPanel();
        btnCalculateCone = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRadiusCone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSideCone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtHeighCone = new javax.swing.JTextField();
        jpnFrustum = new javax.swing.JPanel();
        btnCalculateFrustum = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtRadius1Frustum = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtHeighFrustum = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtRadius2Frustum = new javax.swing.JTextField();
        btnSphere = new javax.swing.JButton();
        btnCylinder = new javax.swing.JButton();
        btnCube = new javax.swing.JButton();
        btnFrustum = new javax.swing.JButton();
        txtAreaSolids = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVolumenSolids = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(645, 440));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Sólidos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 10, 110, 40);

        btnCone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphic/pictures/cono.png"))); // NOI18N
        btnCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCone);
        btnCone.setBounds(180, 80, 80, 90);

        jpnMaster.setLayout(null);
        jLayeredPane1.add(jpnMaster);
        jpnMaster.setBounds(10, 0, 250, 160);

        jpnCube.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnCube.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Cube");
        jpnCube.add(jLabel9);
        jLabel9.setBounds(30, 20, 80, 15);

        btnCalculateCube.setText("Calcular");
        btnCalculateCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateCubeActionPerformed(evt);
            }
        });
        jpnCube.add(btnCalculateCube);
        btnCalculateCube.setBounds(141, 90, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Lado:");
        jpnCube.add(jLabel10);
        jLabel10.setBounds(30, 60, 40, 15);
        jpnCube.add(txtSideCube);
        txtSideCube.setBounds(79, 60, 70, 20);

        jLayeredPane1.add(jpnCube);
        jpnCube.setBounds(10, 0, 250, 140);

        jpnSphere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnSphere.setLayout(null);

        btnCalculateSphere.setText("Calcular");
        btnCalculateSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateSphereActionPerformed(evt);
            }
        });
        jpnSphere.add(btnCalculateSphere);
        btnCalculateSphere.setBounds(140, 110, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Esfera");
        jpnSphere.add(jLabel3);
        jLabel3.setBounds(20, 20, 50, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Radio :");
        jpnSphere.add(jLabel7);
        jLabel7.setBounds(20, 50, 50, 15);
        jpnSphere.add(txtRadiusSphere);
        txtRadiusSphere.setBounds(80, 50, 70, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Altura :");
        jpnSphere.add(jLabel8);
        jLabel8.setBounds(20, 80, 50, 15);
        jpnSphere.add(txtHeighSphere);
        txtHeighSphere.setBounds(80, 80, 70, 20);

        jLayeredPane1.add(jpnSphere);
        jpnSphere.setBounds(10, 0, 250, 150);

        jpnCylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnCylinder.setLayout(null);

        btnCalculateCylinder.setText("Calcular");
        btnCalculateCylinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateCylinderActionPerformed(evt);
            }
        });
        jpnCylinder.add(btnCalculateCylinder);
        btnCalculateCylinder.setBounds(140, 110, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Cilindro");
        jpnCylinder.add(jLabel11);
        jLabel11.setBounds(20, 15, 90, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Altura :");
        jpnCylinder.add(jLabel12);
        jLabel12.setBounds(20, 50, 50, 15);
        jpnCylinder.add(txtHeighCylinder);
        txtHeighCylinder.setBounds(80, 50, 70, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Radio :");
        jpnCylinder.add(jLabel13);
        jLabel13.setBounds(20, 80, 50, 15);
        jpnCylinder.add(txtRadiusCylinder);
        txtRadiusCylinder.setBounds(80, 80, 70, 20);

        jLayeredPane1.add(jpnCylinder);
        jpnCylinder.setBounds(10, 0, 250, 150);

        jpnCone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnCone.setLayout(null);

        btnCalculateCone.setText("Calcular");
        btnCalculateCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateConeActionPerformed(evt);
            }
        });
        jpnCone.add(btnCalculateCone);
        btnCalculateCone.setBounds(150, 120, 90, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Cono");
        jpnCone.add(jLabel14);
        jLabel14.setBounds(20, 10, 100, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Radio :");
        jpnCone.add(jLabel15);
        jLabel15.setBounds(20, 40, 50, 15);
        jpnCone.add(txtRadiusCone);
        txtRadiusCone.setBounds(80, 40, 70, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Lado :");
        jpnCone.add(jLabel16);
        jLabel16.setBounds(20, 100, 50, 15);
        jpnCone.add(txtSideCone);
        txtSideCone.setBounds(80, 100, 70, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Altura :");
        jpnCone.add(jLabel17);
        jLabel17.setBounds(20, 70, 50, 15);
        jpnCone.add(txtHeighCone);
        txtHeighCone.setBounds(80, 70, 70, 20);

        jLayeredPane1.add(jpnCone);
        jpnCone.setBounds(10, 0, 250, 150);

        jpnFrustum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnFrustum.setLayout(null);

        btnCalculateFrustum.setText("Calcular");
        btnCalculateFrustum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateFrustumActionPerformed(evt);
            }
        });
        jpnFrustum.add(btnCalculateFrustum);
        btnCalculateFrustum.setBounds(150, 120, 90, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Frustum");
        jpnFrustum.add(jLabel20);
        jLabel20.setBounds(20, 10, 100, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Radio 1:");
        jpnFrustum.add(jLabel22);
        jLabel22.setBounds(20, 40, 50, 15);
        jpnFrustum.add(txtRadius1Frustum);
        txtRadius1Frustum.setBounds(80, 40, 70, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Altura:");
        jpnFrustum.add(jLabel23);
        jLabel23.setBounds(20, 100, 50, 15);
        jpnFrustum.add(txtHeighFrustum);
        txtHeighFrustum.setBounds(80, 100, 70, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Radio 2:");
        jpnFrustum.add(jLabel24);
        jLabel24.setBounds(20, 70, 50, 15);
        jpnFrustum.add(txtRadius2Frustum);
        txtRadius2Frustum.setBounds(80, 70, 70, 20);

        jLayeredPane1.add(jpnFrustum);
        jpnFrustum.setBounds(10, 0, 250, 150);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(310, 90, 260, 160);

        btnSphere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphic/pictures/esfera.png"))); // NOI18N
        btnSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSphereActionPerformed(evt);
            }
        });
        getContentPane().add(btnSphere);
        btnSphere.setBounds(50, 80, 80, 90);

        btnCylinder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphic/pictures/cilindro.png"))); // NOI18N
        btnCylinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCylinderActionPerformed(evt);
            }
        });
        getContentPane().add(btnCylinder);
        btnCylinder.setBounds(180, 190, 80, 90);

        btnCube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphic/pictures/cubo.png"))); // NOI18N
        btnCube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCube);
        btnCube.setBounds(50, 190, 80, 90);

        btnFrustum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphic/pictures/frustum.png"))); // NOI18N
        btnFrustum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrustumActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrustum);
        btnFrustum.setBounds(50, 300, 80, 90);
        getContentPane().add(txtAreaSolids);
        txtAreaSolids.setBounds(390, 260, 70, 20);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Volumen:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 300, 57, 21);
        getContentPane().add(txtVolumenSolids);
        txtVolumenSolids.setBounds(410, 300, 80, 20);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Area: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 260, 50, 21);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initializePanelsSolids(){
        
        this.jpnSphere.setVisible(false);
        this.jpnCube.setVisible(false);
        this.jpnCone.setVisible(false);
        this.jpnCylinder.setVisible(false);
        this.jpnFrustum.setVisible(false);

    }
    
    private void btnConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConeActionPerformed
        initializePanelsSolids();
        jpnMaster.setVisible(false);
        jpnCone.setVisible(true);
        txtRadiusCone.setText("");
        txtHeighCone.setText("");
        txtSideCone.setText("");
        
    }//GEN-LAST:event_btnConeActionPerformed

    private void btnSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSphereActionPerformed
        initializePanelsSolids();
        jpnMaster.setVisible(false);
        jpnSphere.setVisible(true);
        txtRadiusSphere.setText("");
        txtHeighSphere.setText("");

    }//GEN-LAST:event_btnSphereActionPerformed

    private void btnCylinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCylinderActionPerformed
        initializePanelsSolids();
        jpnMaster.setVisible(false);
        jpnCylinder.setVisible(true);
        txtHeighCylinder.setText("");
        txtRadiusCylinder.setText("");
    }//GEN-LAST:event_btnCylinderActionPerformed

    private void btnCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubeActionPerformed
        initializePanelsSolids();
        jpnMaster.setVisible(false);
        jpnCube.setVisible(true);
        txtSideCube.setText("");
    }//GEN-LAST:event_btnCubeActionPerformed

    private void btnFrustumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrustumActionPerformed
        initializePanelsSolids();
        jpnMaster.setVisible(false);
        jpnFrustum.setVisible(true);
        txtRadius1Frustum.setText("");
        txtRadius2Frustum.setText("");
        txtHeighFrustum.setText("");
    }//GEN-LAST:event_btnFrustumActionPerformed

    private void btnCalculateSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateSphereActionPerformed
        txtAreaSolids.setText("");
        txtVolumenSolids.setText("");
        if(!((this.txtRadiusSphere.getText().equals(""))||(this.txtHeighSphere.getText().equals("")))){
            try{
                float radius= Float.parseFloat(this.txtRadiusSphere.getText());
                float heigh= Float.parseFloat(this.txtHeighSphere.getText());
                Sphere s = new Sphere(heigh, radius);
                txtAreaSolids.setText(s.CalculateArea().toString());
                txtVolumenSolids.setText(s.CalculateVolume().toString());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "No es un número");
                txtRadiusSphere.setText("");
                txtHeighSphere.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Campos incompletos");
            txtRadiusSphere.setText("");
            txtHeighSphere.setText("");
        }
    }//GEN-LAST:event_btnCalculateSphereActionPerformed

    private void btnCalculateCubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateCubeActionPerformed
        txtAreaSolids.setText("");
        txtVolumenSolids.setText("");
        if(!this.txtSideCube.getText().equals("")){
            try{
                float side= Float.parseFloat(txtSideCube.getText());
                Cube cu = new Cube(side);
                txtAreaSolids.setText(cu.CalculateArea().toString());
                txtVolumenSolids.setText(cu.CalculateVolume().toString());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "No es un número");
                txtSideCube.setText("");
            }
            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Campos incompletos");
            txtSideCube.setText("");
        }
    }//GEN-LAST:event_btnCalculateCubeActionPerformed

    private void btnCalculateCylinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateCylinderActionPerformed
        txtAreaSolids.setText("");
        txtVolumenSolids.setText("");
        if(!((this.txtHeighCylinder.getText().equals(""))||(this.txtRadiusCylinder.getText().equals("")))){
            try{
                float heigh= Float.parseFloat(this.txtHeighCylinder.getText());
                float radius= Float.parseFloat(this.txtRadiusCylinder.getText());
                Cylinder cy = new Cylinder (heigh, radius);
                txtAreaSolids.setText(cy.CalculateArea().toString());
                txtVolumenSolids.setText(cy.CalculateVolume().toString());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "No es un número");
                txtHeighCylinder.setText("");
                txtRadiusCylinder.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Campos incompletos");
            txtHeighCylinder.setText("");
            txtRadiusCylinder.setText("");
        }
    }//GEN-LAST:event_btnCalculateCylinderActionPerformed

    private void btnCalculateConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateConeActionPerformed
        txtAreaSolids.setText("");
        txtVolumenSolids.setText("");
        if(!((this.txtRadiusCone.getText().equals(""))||(this.txtHeighCone.getText().equals(""))||(this.txtSideCone.getText().equals("")))){
            try{
                float radius= Float.parseFloat(this.txtRadiusCone.getText());
                float heigh= Float.parseFloat(this.txtHeighCone.getText());
                float side= Float.parseFloat(this.txtSideCone.getText());
                Cone c = new Cone(side, heigh, radius);
                txtAreaSolids.setText(c.CalculateArea().toString());
                txtVolumenSolids.setText(c.CalculateVolume().toString());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "No es un número");
                txtRadiusCone.setText("");
                txtHeighCone.setText("");
                txtSideCone.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Campos incompletos");
            txtRadiusCone.setText("");
            txtHeighCone.setText("");
            txtSideCone.setText("");
        }
    }//GEN-LAST:event_btnCalculateConeActionPerformed

    private void btnCalculateFrustumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateFrustumActionPerformed
        txtAreaSolids.setText("");
        txtVolumenSolids.setText("");
        if(!((this.txtRadius1Frustum.getText().equals(""))||(this.txtRadius2Frustum.getText().equals(""))||(this.txtHeighFrustum.getText().equals("")))){
            try{
                float radius1= Float.parseFloat(this.txtRadius1Frustum.getText());
                float heigh= Float.parseFloat(this.txtHeighFrustum.getText());
                float radius2= Float.parseFloat(this.txtRadius2Frustum.getText());
                Frustum f = new Frustum(heigh, radius2, radius1);
                txtAreaSolids.setText(f.CalculateArea().toString());
                txtVolumenSolids.setText(f.CalculateVolume().toString());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "No es un número");
                txtRadius1Frustum.setText("");
                txtRadius2Frustum.setText("");
                txtHeighFrustum.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Campos incompletos");
            txtRadius1Frustum.setText("");
            txtRadius2Frustum.setText("");
            txtHeighFrustum.setText("");
        }
    }//GEN-LAST:event_btnCalculateFrustumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSolidsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSolidsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSolidsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSolidsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSolidsMenu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateCone;
    private javax.swing.JButton btnCalculateCube;
    private javax.swing.JButton btnCalculateCylinder;
    private javax.swing.JButton btnCalculateFrustum;
    private javax.swing.JButton btnCalculateSphere;
    private javax.swing.JButton btnCone;
    private javax.swing.JButton btnCube;
    private javax.swing.JButton btnCylinder;
    private javax.swing.JButton btnFrustum;
    private javax.swing.JButton btnSphere;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jpnCone;
    private javax.swing.JPanel jpnCube;
    private javax.swing.JPanel jpnCylinder;
    private javax.swing.JPanel jpnFrustum;
    private javax.swing.JPanel jpnMaster;
    private javax.swing.JPanel jpnSphere;
    private javax.swing.JTextField txtAreaSolids;
    private javax.swing.JTextField txtHeighCone;
    private javax.swing.JTextField txtHeighCylinder;
    private javax.swing.JTextField txtHeighFrustum;
    private javax.swing.JTextField txtHeighSphere;
    private javax.swing.JTextField txtRadius1Frustum;
    private javax.swing.JTextField txtRadius2Frustum;
    private javax.swing.JTextField txtRadiusCone;
    private javax.swing.JTextField txtRadiusCylinder;
    private javax.swing.JTextField txtRadiusSphere;
    private javax.swing.JTextField txtSideCone;
    private javax.swing.JTextField txtSideCube;
    private javax.swing.JTextField txtVolumenSolids;
    // End of variables declaration//GEN-END:variables
}
